# Generated by Django 5.2.7 on 2025-12-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0009_district_alter_news_category_alter_news_district'),
        ('mynews', '0010_adminotp'),
    ]

    operations = [
    ]
